import assert from 'node:assert/strict';
import {seedState,createIssue,transition,canAct,createStore,photoError,fileError} from '../../resources/js/qic/state.js';
import {workbook} from '../../resources/js/qic/export.js';
import {writeFile} from 'node:fs/promises';
const payload={material:'Housing',defect:'Goresan',description:'Uji',quantity:3,occurredAt:'2026-10-03T08:00',photos:{defect:'d.png',label:'l.png'}};
let i=createIssue(seedState(),payload,true); const step=(r,a,p={})=>i=transition(i,r,a,p);
assert.throws(()=>transition(i,'auto-line','verify',{reason:'ok'}));
assert.throws(()=>transition(i,'quality','verify'));
step('quality','return_info',{reason:'Lengkapi deskripsi'});step('main-assy','submit',payload);
step('quality','verify',{reason:'Valid'});step('quality','assign',{owner:'Auto Line 1'});step('auto-line','acknowledge');
step('auto-line','save_investigation',{investigation:'Tray',containment:'Pisahkan',evidence:['a.pdf']});
const c={concern:'Goresan',cause:'Tray',countermeasure:'Separator',evidence:['b.pdf']};
assert.throws(()=>transition(i,'auto-line','submit_response',{...c,evidence:[]}));
step('auto-line','submit_response',c);step('quality','revise',{reason:'Lengkapi bukti'});const old=structuredClone(i.versions[0]);
step('auto-line','save_response',{...c,cause:'Kontak tray'});step('auto-line','submit_response',{...c,cause:'Kontak tray'});
assert.equal(i.versions.length,2);assert.deepEqual(i.versions[0],old);
step('quality','approve',{reason:'Cukup'});assert.throws(()=>transition(i,'auto-line','submit_corrective',{action:'Pasang'}));
const action={action:'Pasang separator',result:'Sesuai',evidence:['c.jpg']};step('auto-line','submit_corrective',action);
step('quality','return_corrective',{reason:'Uji ulang'});step('auto-line','submit_corrective',action);step('quality','close',{reason:'Lulus'});
assert.equal(i.status,'closed');assert.equal(canAct(i,'quality','cancel'),false);assert.throws(()=>transition(i,'auto-line','submit_response',c));
assert.throws(()=>createIssue(seedState(),{...payload,photos:{}},true));assert.equal(createIssue(seedState(),{material:'Draft'},false).status,'draft');
const m=new Map(),storage={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};let s=createStore(storage,1);s.save({...s.get(),counter:20});assert.equal(createStore(storage,1).get().counter,20);
const blocked=createStore({getItem(){throw Error()},setItem(){throw Error()}},2);blocked.save(seedState());assert.ok(blocked.warning());
assert.equal(photoError({type:'image/png',size:10}), '');assert.ok(photoError({type:'application/pdf',size:10}));assert.ok(fileError({type:'image/png',size:6*1024*1024}));
if(process.argv[2])await writeFile(process.argv[2],Buffer.from(await workbook([['ID','Catatan'],['QI-001','<& =SUM(A1)']]).arrayBuffer()));
console.log('PASS: workflow lintas role, revisi immutable, validasi, pembatasan aksi, session storage, berkas, dan pembuatan XLSX.');
