<?php

return [
    'main-assy' => ['label' => 'Main Assy', 'subtitle' => 'Internal Customer', 'pages' => [
        'dashboard' => ['title' => 'Dashboard', 'screen' => 'dashboard', 'path' => '/dashboard', 'nav' => true],
        'issues.index' => ['title' => 'Issue Saya', 'screen' => 'issues', 'path' => '/issues', 'nav' => true],
        'issues.create' => ['title' => 'Buat Complaint', 'screen' => 'create', 'path' => '/issues/create', 'nav' => true],
        'issues.show' => ['title' => 'Detail Issue', 'screen' => 'detail', 'path' => '/issues/{issue}', 'nav' => false],
        'issues.edit' => ['title' => 'Lengkapi Complaint', 'screen' => 'edit', 'path' => '/issues/{issue}/edit', 'nav' => false],
        'tracking' => ['title' => 'Tracking Issue', 'screen' => 'tracking', 'path' => '/tracking', 'nav' => true],
        'notifications' => ['title' => 'Notifikasi', 'screen' => 'notifications', 'path' => '/notifications', 'nav' => true],
        'profile' => ['title' => 'Profil', 'screen' => 'profile', 'path' => '/profile', 'nav' => true],
    ]],
    'auto-line' => ['label' => 'Auto Line', 'subtitle' => 'Process Owner', 'pages' => [
        'dashboard' => ['title' => 'Dashboard', 'screen' => 'dashboard', 'path' => '/dashboard', 'nav' => true],
        'issues.index' => ['title' => 'Penugasan Saya', 'screen' => 'issues', 'path' => '/issues', 'nav' => true],
        'issues.show' => ['title' => 'Investigasi dan Containment', 'screen' => 'investigation', 'path' => '/issues/{issue}', 'nav' => false],
        'responses.index' => ['title' => 'Respons 3C', 'screen' => 'responses', 'path' => '/responses', 'nav' => true],
        'responses.create' => ['title' => 'Susun Respons 3C', 'screen' => 'response-form', 'path' => '/responses/{issue}/create', 'nav' => false],
        'responses.show' => ['title' => 'Detail Respons 3C', 'screen' => 'response-detail', 'path' => '/responses/{issue}', 'nav' => false],
        'responses.revise' => ['title' => 'Revisi Respons 3C', 'screen' => 'response-form', 'path' => '/responses/{issue}/revise', 'nav' => false],
        'corrective' => ['title' => 'Tindakan Korektif', 'screen' => 'corrective', 'path' => '/issues/{issue}/corrective', 'nav' => false],
        'history' => ['title' => 'Riwayat Penanganan', 'screen' => 'history', 'path' => '/history', 'nav' => true],
        'notifications' => ['title' => 'Notifikasi', 'screen' => 'notifications', 'path' => '/notifications', 'nav' => true],
        'profile' => ['title' => 'Profil', 'screen' => 'profile', 'path' => '/profile', 'nav' => true],
    ]],
    'quality' => ['label' => 'Quality', 'subtitle' => 'Verifier dan Decision Controller', 'pages' => [
        'dashboard' => ['title' => 'Quality Control Dashboard', 'screen' => 'dashboard', 'path' => '/dashboard', 'nav' => true],
        'issues.index' => ['title' => 'Seluruh Issue', 'screen' => 'issues', 'path' => '/issues', 'nav' => true],
        'issues.show' => ['title' => 'Detail Issue', 'screen' => 'detail', 'path' => '/issues/{issue}', 'nav' => false],
        'issues.verify' => ['title' => 'Verifikasi Issue', 'screen' => 'verify', 'path' => '/issues/{issue}/verify', 'nav' => false],
        'assignments' => ['title' => 'Penugasan Auto Line', 'screen' => 'assignments', 'path' => '/assignments', 'nav' => true],
        'reviews.index' => ['title' => 'Antrean Review 3C', 'screen' => 'reviews', 'path' => '/reviews', 'nav' => true],
        'reviews.show' => ['title' => 'Review Respons 3C', 'screen' => 'review', 'path' => '/reviews/{issue}', 'nav' => false],
        'final-verification' => ['title' => 'Verifikasi Akhir dan Closure', 'screen' => 'final', 'path' => '/issues/{issue}/final', 'nav' => false],
        'sla-monitoring' => ['title' => 'Monitoring SLA', 'screen' => 'sla', 'path' => '/sla-monitoring', 'nav' => true],
        'ai-insights' => ['title' => 'AI Insight', 'screen' => 'ai', 'path' => '/ai-insights', 'nav' => true],
        'reports' => ['title' => 'Laporan', 'screen' => 'reports', 'path' => '/reports', 'nav' => true],
        'audit-log' => ['title' => 'Audit Log', 'screen' => 'audit', 'path' => '/audit-log', 'nav' => true],
        'master-data' => ['title' => 'Master Data', 'screen' => 'master', 'path' => '/master-data', 'nav' => true],
        'notifications' => ['title' => 'Notifikasi', 'screen' => 'notifications', 'path' => '/notifications', 'nav' => true],
        'profile' => ['title' => 'Profil', 'screen' => 'profile', 'path' => '/profile', 'nav' => true],
    ]],
];
